### ISSUE TITLE
Error: Cannot find module 'debug'  after git pull tonight 11/2/19

### ISSUE THREAD

**Issue by trecement** [theWebalyst/safe-drive#11]
Coming back to SAFE Drive after a period of inactivity on SAFE, I did a git pull to update 

```
willie@gagarin:~/projects/maidsafe/safe-drive$ ls -al
total 284
drwxr-xr-x  7 willie willie   4096 Feb  3 22:24 .
drwxrwxr-x 30 willie willie   4096 Feb 12 00:44 ..
-rwxr-xr-x  1 willie willie   5465 Feb  3 22:21 bin.js
-rw-r--r--  1 willie willie    565 Feb  3 22:24 debug.log
drwxr-xr-x  4 willie willie   4096 Feb  3 22:21 docs
drwxr-xr-x  8 willie willie   4096 Feb 12 03:17 .git
-rw-r--r--  1 willie willie   1093 Feb  3 22:21 .gitignore
-rw-r--r--  1 willie willie  35147 Feb  3 22:21 LICENSE
-rw-r--r--  1 willie willie   3288 Feb  3 22:21 package.json
-rw-r--r--  1 willie willie  18612 Feb  3 22:21 README.md
drwxr-xr-x  2 willie willie   4096 Feb  3 22:21 releases-node-files
drwxr-xr-x  4 willie willie   4096 Feb  3 22:21 src
drwxr-xr-x  3 willie willie   4096 Feb 12 03:17 tests
-rw-r--r--  1 willie willie 183688 Feb  3 22:21 yarn.lock
willie@gagarin:~/projects/maidsafe/safe-drive$ DEBUG=safe* node bin.js 2>&1 | tee debug.log
module.js:550
    throw err;
    ^

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/willie/projects/maidsafe/safe-drive/bin.js:3:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

willie@gagarin:~/projects/maidsafe/safe-drive$ node --version
v8.15.0
```
Ubuntu 18.04 

[debug.log](https://github.com/theWebalyst/safe-drive/files/2854013/debug.log)       simply contains the few lines above.

**Comment by theWebalyst** [comment]
Thanks Willie, and for coming back to help too - it's been a bit lonely here lately 😄

I think this is my cock up - looks like I've somehow dropped module `debug` from the dependencies. So do `yarn add debug` and try again. If that doesn't work let's see your `git status` output too. Good luck!

Closing now, but reopen if not solved.

**Comment by trecement** [comment]
Yep - sorted :-)   thank you.
